# Generated by Django 3.1 on 2022-06-03 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='GSTIN',
            new_name='gstin',
        ),
    ]
